---
- rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Add repository
  yum_repository:
    name: jenkins
    description: Jenkins REPO
    baseurl: http://pkg.jenkins.io/redhat-stable 

- name: Jenkins Install
  yum:
    name: jenkins
    state: present
  become: yes
  notify:
    - restart jenkins

- name: Install yum utils
  yum:
    name: git
    state: latest

- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest

- name: Install lvm2
  yum:
    name: lvm2
    state: latest

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0
  become: yes

- name: Enable Docker Test repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-test'
    option: enabled
    value: 0
  become: yes

- name: Install Docker
  package:
    name: docker-ce
    state: latest
  become: yes
  notify:
    - restart docker

- name: Enable Docker
  systemd:
    name: docker
    state: started
    enabled: True

- name: adding existing user jenkins to group docker
  user:
    name: jenkins
    groups: docker,root
    append: yes
